apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: sample-k8s-app-container
        image: swr.la-south-2.myhuaweicloud.com/hwperu/test-jenkins:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: default-secret